### ISSUE TITLE
Error: attribute 'xetex-def' missing

### ISSUE THREAD

**Issue by vakili** [matthewbauer/resume#1]
First of all, thank you for making this.

I tried the following on NixOS 18.03:
`git clone https://github.com/matthewbauer/resume/`
`cd resume`
`emacs README.org`
then in emacs, ran `org-babel-tangle` which succeeds. Now when I run
`nix-build resume.nix`
I get `error: attribute 'xetex-def' missing`.

I suspect that recent changes in nixpkgs are causing this, but I cannot find information about `xetex-def`. Could you please look into this?

**Comment by matthewbauer** [comment]
Most likely that one doesn't exist anymore. I would try just removing it in README.org's resume.nix section:

https://github.com/matthewbauer/resume/blob/master/README.org#resumenix

I haven't used this in a while but it hopefully will still work.

**Comment by vakili** [comment]
Works on Nixos 18.09. Closing this issue. Thanks again.
