### ISSUE TITLE
Spacing between first and last name?

### ISSUE THREAD

**Issue by phren0logy** [matthewbauer/resume#2]
Apologies for such a basic question, but when I add my degree after my last name, the spacing between first, last, and degree is thrown off by the formatting expecting only a first and last name.

For example, I've tried:
`\name{John}{Doe PhD}`
and
`\name{John Doe PhD}{}`
with no luck.

I have tried adjustments to HeaderAfterNameSkip and a few other possible candidates, but quickly run up against my limitations with LaTeX, and I suspect that the \ifthenelse part of the header with \raggedright and \raggedleft is where I need to look, but I can't untangle it.

Could I trouble you to help me figure out how I can center the whole thing?

**Comment by matthewbauer** [comment]
Yeah that seems useful to have. This just adds a 3rd field in the name, that should be spaced equally to first and last.
